# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: 星星
url: http://gsven.github.io/
feed: /atom.xml
author_info: <a href="http://gsven.github.io/">gsven</a>

myblog:
  gavatar: images/2.jpg
  gpname: gsven
  linkedin: http://www.linkedin.com/in/gsven
  github: https://github.com/GSven
  email: mailto:g.sven@jiangwei.bid
  coverimgs: []
  postbgimg: []

categories: [python, books]
